### PR TITLE
DEV-174

### PR DESCRIPTION
**Pull request by A-amon**
Update repository name to title case
- Add function to remove hyphen
- Add function to capitalize every word in sentence

### CODE REVIEW

**Review by J3ffJessie — APPROVED** [review]
Awesome job @A-amon this functions perfectly and does a great job of cleaning up the Repo names.  Makes it look official and professional.  Code is very clean and documented.  Awesome job.

**Comment by mateahoward** [comment]
Guys did we have a ticket for this?

**Comment by J3ffJessie** [comment]
@A-amon just need to merge main into your branch to clear up conflicts and we should be good to merge.

**Comment by A-amon** [comment]
Yayyy! 🥳

**Comment by A-amon** [comment]
Conflicts resolved~ 😊

**Comment by J3ffJessie** [comment]
I can't merge but once Likii is settled in the new house it will get merged in. Thanks again for working on this. @A-amon

**Comment by A-amon** [comment]
😁No problem!

**Pull request merged**
