### PR TITLE
Add all images in reference to DEV-189 Jira Ticket into assets folder…

### PR DESCRIPTION
**Pull request by J3ffJessie**
….  Add images to the colored backgrounds in the technologies used section to reflect the technologies used by JDG

This is in reference to DEV-189 Jira Ticket to add logos to technologies used.  Added transparent images to the assets folder, then input the images into the colored blocks.  Pending review to see which logos fit best design wise and if the sizing is correct or needs adjusted to make it look as best as possible.  

There are not many logos out there that are easy to get a hold of.

### CODE REVIEW

**Comment by mateahoward** [comment]
Hey @J3ffJessie 😄 Fab job again! Thank you very much for adding them in 😄

I have a small bit of feedback for you and would like you to make a tiny change for that if that's alright? 

**In index.html, from line 179 until line 190** we have added images with inline-styling. 

That is not usually recommended 😅(sometimes is, when we _really_ need them, but otherwise not really recommended). When we write styling in-line, these styles have the power to override other styles set elsewhere and in general, are very hard to keep track of + you have to manually add them in on each line you'll want to use them 😄

What we do in this case is we look at the` ` element and its parent (div around it) and see if there is a` 'class' `set already. Then we'd go to a CSS file and target that 'parent' class and just add 'img' next to it and place our height's and width's there 😄

**If you fancy going a step further,** the bottom two images look a bit stretched 😄 Just as an exercise try setting a percentage value for width and height instead of a fixed value with pixels and see if you learn something new playing with percentages 😄

**Comment by J3ffJessie** [comment]
Will do. I'll take a look at the classes and see if I can move the styling over to the actual CSS file and use percentage to adjust and see size change on the stretched images. Appreciate the feedback.

**Comment by J3ffJessie** [comment]
@mateahoward Added different images for referencing that I feel fit better overall style wise with the rest of the chosen logos.  Moved Styling from inline to the actual CSS file as advised.  Changed from px sizing to percentages.  Added the files and folder from DEV-218/219/220 tickets as well to get all of those tickets wrapped into one PR. Appreciate any other feedback you have.  If we are looking for different logos just let me know and I will dig around and create them if need be to make it work.

**Comment by J3ffJessie** [comment]
Added alt tags to all images for accessibility bay I forgot to add in earlier. Should be good for review and I'll take any feedback and make corrections as needed. Appreciate it.

**Review by mateahoward — APPROVED** [review]

**Comment by mateahoward** [comment]
Fantastic job @J3ffJessie This is now being merged in :D Thank you very much for doing all the changes :D

**Pull request merged**
