### PR TITLE
Dev 213

### PR DESCRIPTION
**Pull request by A-amon**
Sort contributors by contributions
Descending order (Largest to smallest)

### CODE REVIEW

**Comment by mateahoward** [comment]
hey @A-amon :D I'm not sure I can see your change here? We seem to have a lot of formatting changes, do you mind commenting on the rows you have changed to point them out or maybe sending another PR without formatting changes (spaces)?

**Comment by A-amon** [comment]
Oops, the auto-formatting! 😂 I left a comment for my part. If viewed on Github, it would be lines 54 - 57. 😀

**Comment by J3ffJessie** [comment]
This looks good functionally, however I think we need to get better clarification on where we want to implement this on the Dashboard since there are two different areas where users are showing up at.  I will approve your changes here as they aren't breaking changes or anything but @mateahoward can we dive into the Dashboard a little more to address exactly where this functionality needs to be applied and possibly eliminate some duplication on the dashboard as it sits right now.  Good job @A-amon

**Review by J3ffJessie — APPROVED** [review]

**Comment by A-amon** [comment]
Thank you! 🥳

**Pull request merged**
