### PR TITLE
JDG-DEV-225-NAVBAR-COMPONENT

### PR DESCRIPTION
**Pull request by Loop-infinity**
Moved repetitive navbar html into a component that can be reused.

### CODE REVIEW

**Review by J3ffJessie — DISMISSED** [review]
Very well done. Clean and thorough. Nice job @Loop-infinity

**Comment by Loop-infinity** [comment]
Thanks, @J3ffJessie .

**Comment by mateahoward** [comment]
Hello hello 😀 would you guys mind changing it from main to dev branch old? Won't let me do it over the phone for some reason 😅 there might also be some conflicts as I merged a change a min ago to dev branch as well 😁

@Loop-infinity

**Comment by J3ffJessie** [comment]
Not sure if I'm able to do this or not. I'll try to check if Loop doesn't tackle it before I get there.

**Review by J3ffJessie — APPROVED** [review]
Thank you @Loop-infinity for switching the branch.  I was just jumping on to figure it out.  @mateahoward merge ready.

**Comment by mateahoward** [comment]
Done and done 👍 thank you both 😄

**Pull request merged**
