### PR TITLE
updated teammembers.js

### PR DESCRIPTION
**Pull request by Lokesh-Rathore**

### CODE REVIEW

**Comment by mateahoward** [comment]
Hey @Lokesh-Rathore 😎 would you be okay resolving conflicts (you can do this by pulling from dev branch and then merging it into yours)? 

Let me know if you need help ☺️

**Comment by Lokesh-Rathore** [comment]
I updated the conflicts just take a review and let me know if anything's wrong

**Review by J3ffJessie — APPROVED** [review]

**Comment by mateahoward** [comment]
@Lokesh-Rathore we forgot to push to 'dev' branch instead of 'main'. I'll change it now but be careful for the future please :)

**Review by mateahoward — APPROVED** [review]

**Comment by Lokesh-Rathore** [comment]
Sorry, I'll keep in mind from next time

**Pull request merged**
