### PR TITLE
Preparing for hacktoberfest

### PR DESCRIPTION
**Pull request by mateahoward**

### CODE REVIEW

**Comment by mateahoward** [comment]
Pls check if everything works on your ends and let me know if not :)

**Comment by J3ffJessie** [comment]
I'll check this afternoon and make sure everything works. Question, it says non-profit organization. Is JDG registered as an NPO or just stating we are non-profit? Unsure of the legal issues if we misrepresent as a non-profit if we aren't registered as one. Had issues with this in another group taking donations as an NPO and it wasn't but that was stateside.

**Comment by mateahoward** [comment]
thank you @J3ffJessie :D ah :D I just wanted to say there is no money involved so non-profit seemed okay :D :D what do you think we should put?

**Comment by J3ffJessie** [comment]
Not entirely sure. I'll do some searching and see if I can find anything about it.

**Comment by mateahoward** [comment]
To save us trouble, do you think 'subscription-free' or 'Fee-Free' would do the job?

**Comment by J3ffJessie** [comment]
Yeah, everything I'm finding online says legally we would have to register for tax exemption to legally be protected as a non profit or not for profit. I think we can list that we are open source and we accept donations but not list that we are non profit. We accept sponsorship or something like that.

**Review by J3ffJessie — CHANGES_REQUESTED** [review]
Remove non profit for legal reasons. Need to verify links on navbar correspond correctly. Some of the navbar links don't navigate to anywhere. @mateahoward

**Comment by mateahoward** [comment]
Changed copy, and hopefully sorted out all navbars :D

**Comment by J3ffJessie** [comment]
Just seeing this. I'll try to check in the morning and approve.

**Review by J3ffJessie — APPROVED** [review]

**Comment by mateahoward** [comment]
thank you very much for all this @J3ffJessie :D

**Pull request merged**
