### PR TITLE
Dev 254 dashboard style and populate dashboard sidebar to match new designs

### PR DESCRIPTION
**Pull request by Denice-S**
# Please fill out the PR template below 

- [ x] Have you named your branch after a Jira ticket?
- [x ] Have you pulled from 'dev' branch before creating this PR to make sure there are no conflicts present
- [ x] Have you checked if your PR is merging into the correct branch?
- [ x] Have you set yourself as the assignee on this PR?
- [ x] Have you requested a reviewer?
- [ x] Have you updated your Jira ticket to QA status?

## Please add your ticket's number at the end of the link below:

https://junior-developer-group.atlassian.net/browse/254

## Please describe your change below: 

styled the sidebar according to the figma file on the ticket.
.
.

### Testing your code

- [ ] I have ran Chrome LightHouse tool to make sure there are no accessibility issues
- [ ] I have run ARC Toolkit to make sure there are no accessibility issues
- [ ] I have tested the change across multiple devices and it's stayed responsive (including mobile phones 280px width)

Other:
- [ x] I have tested my code using [ DESCRIBE YOUR TESTING HERE ]
checked no accessibility issues arising from lighthouse with regards to sidebar but cannot test responsiveness very well due to the main page not being styled correctly

### CODE REVIEW

**Comment by mateahoward** [comment]
Hey @Denice-S, just checking to see if this PR is ready? :D

**Comment by Denice-S** [comment]
> Hey @Denice-S, just checking to see if this PR is ready? :D

Hey, Sorry for inactivity on this -  Ill update this over the weekend and ping you as we are running out of July !!!

**Comment by Denice-S** [comment]
hey @mateahoward  , ive made some final changes -can you take a look over it  and let me know if anything else needs amending.

**Review by mateahoward — APPROVED** [review]

**Comment by mateahoward** [comment]
Hey @Denice-S all looking very good :D thank you very much for doing all this, I know it was a pain ❤️

**Pull request merged**
